spring:

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/subway
    username: sa리
    password:
  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: always
